gettingstarted/urls.py
#admin.autodiscover()

#from django.urls import include, re_path, path
from django.contrib import admin
admin.autodiscover()
from django.urls import include, re_path

from django.contrib.auth import views as auth_views
from hello.views import index, tests

app_name = "gettingstarted"

''' migration to Django 2.2 use re_path '''
urlpatterns = [
    re_path(r'^$', index, name='index'),

    re_path(r'^admin/', admin.site.urls ),
    
    re_path(r'^reservation/', include('reservation.urls') ),
    re_path(r'^partitions/', include('partitions.urls') ),

    re_path(r'^accounts/login/$', auth_views.LoginView.as_view(), name ='login'),
    re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view() , name = 'logout' ),
    #re_path(r'^accounts/profile/$', index , name = 'index'),
    re_path(r'^tests/', tests, name='tests')
]

''' migration to Django 2.2 use re_path '''
urlpatterns += [
    re_path(r'^password_change/', auth_views.PasswordChangeView.as_view(), 
         {'template_name': 'registration/password_change_form.html'} ,name="password_change" ),
    
    re_path(r'^password_change_done/$', auth_views.PasswordChangeDoneView.as_view(), 
         {'template_name': 'registration/password_change_done.html'} ,name="password_change_done" ),
    ]

''' March 2024 - password reset '''
urlpatterns += [

    re_path(r'^password_reset/$', auth_views.PasswordResetView.as_view() ,
        { 'template_name': 'registration/password_reset_form', 'post_reset_redirect' : '/password_reset_done/'}, 
        name="password_reset"),
     
    re_path(r'^password_reset_done/$', auth_views.PasswordResetDoneView.as_view(), 
        { 'template_name' : 'registration/password_reset_done'} ,
        name="password_reset_done"  ) ,
         
    re_path(r'^password_reset_confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 
        auth_views.PasswordResetConfirmView.as_view() , 
        { 'template_name' : 'registration/password_reset_confirm'} ,
        name="password_reset_confirm" ),
     
    re_path(r'^password_reset_complete/$',
        auth_views.PasswordResetCompleteView.as_view() , 
        { 'template_name' : 'registration/password_reset_complete'} ,
        name="password_reset_complete" )
    
    ]

partitions/urls.py
from django.conf.urls import re_path

#from django.views.decorators.csrf import csrf_exempt
from partitions.views import partitions, recordNewPartition, deletePartition, modifyPartition

app_name = "partitions"

urlpatterns = [
               
    re_path(r'^$', partitions, name='partitions'),
    re_path(r'^recordNewPartition$', recordNewPartition , name = 'recordNewPartition'),
    re_path(r'^deletePartition$', deletePartition , name = 'deletePartition'),
    re_path(r'^modifyPartition$', modifyPartition , name = 'modifyPartition'),

]

reservation/urls.py
from django.conf.urls import re_path

from reservation.views.ManageBookings import addBooking, deleteBooking, modifyBooking, deleteOldBookings
from reservation.views.ManageReservations import reservations
from reservation.views.ManagePeriods import modifyPeriod
from reservation.views.WeeklyReservationsViews import generateWeeklyReservations
from reservation.views.ExcelOutput import createExcelOutput 
#from django.views.decorators.csrf import csrf_exempt

app_name = "reservation"

urlpatterns = [
    re_path(r'^$', reservations, name='reservations'),
    
    re_path(r'^modifyPeriod$', modifyPeriod , name = 'modifyPeriod'),
    re_path(r'^addBooking$', addBooking , name = 'addBooking'),
    re_path(r'^deleteBooking$', deleteBooking , name = 'deleteBooking'),
    re_path(r'^modifyBooking$', modifyBooking , name = 'modifyBooking'),
    re_path(r'^generateWeeklyReservations$', generateWeeklyReservations , name = 'generateWeeklyReservations'),
    re_path(r'^deleteOldBookings$', deleteOldBookings , name = 'deleteOldBookings'),
]

''' view to create an EXCEL file '''
urlpatterns += [
    re_path(r'^excel/$', createExcelOutput , name='createExcel'),
]

hello/models.py
#from __future__ import unicode_literals
#from django.utils import timezone

from django.db import models
from django.contrib.auth.models import User
#from django.utils.encoding import python_2_unicode_compatible

# Create your models here.
class Greeting(models.Model):
    when = models.DateTimeField('date created', auto_now_add=True)


#@python_2_unicode_compatible
class SiteMessage(models.Model):
    
    author = models.ForeignKey(User, on_delete=models.CASCADE)

    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    ''' the content of the message '''
    message = models.CharField(max_length=1500, default="")
    active = models.BooleanField(default=False)
    ''' 13th April 2016 - added after discussing with Antoine '''
    event_date = models.DateField(blank=True, null=True)

    def __str__(self):
        strMessage = 'Site Message created: {0}'.format(self.created)
        strMessage += ' is active: {0}'.format(self.active)
        strMessage += ' by: {0}'.format(self.author)
        strMessage += ' modified: {0}'.format(self.modified)
        strMessage += ' --- {0}'.format(self.message)
        return strMessage 

hello/forms.py
'''
Created on 13 avr. 2016

@author: PASTOR Robert
'''

# from .models import SiteMessage
# 
# 
# from django import forms
# #from django.forms.extras.widgets import SelectDateWidget
# 
# class SiteMessageForm(forms.ModelForm):
# 
#     #event_date = forms.DateField(widget=SelectDateWidget())
#     class Meta:
#         model = SiteMessage
#         exclude = ['created', 'modified']
#         
#     def __init__(self, *args, **kwargs):
#         super(SiteMessageForm, self).__init__(*args, **kwargs)
#         self.fields['event_date'].widget.attrs['class'] = 'datepicker'

hello/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from django.core import serializers

from hello.models import Greeting
from hello.models import SiteMessage

# Create your views here.
def index(request):
    # return HttpResponse('Hello from Python!')
    template = loader.get_template('./index.html')

    siteMessages = []
    for siteMessage in SiteMessage.objects.all().order_by("event_date"):
        if siteMessage.active == True:
            siteMessages.append(siteMessage)
            
    siteMessages = serializers.serialize('json', siteMessages)
    
    context = {'siteMessages' : siteMessages}
    return HttpResponse(template.render(context, request))


def db(request):

    greeting = Greeting()
    greeting.save()

    greetings = Greeting.objects.all()
    return render(request, 'db.html', {'greetings': greetings})


def tests(request):
    template = loader.get_template('./tests.html')
    context = {}
    return HttpResponse(template.render(context, request))

hello/templates/base.html
{% load static %}

<?xml version="1.0" encoding="charset=utf-8"?>
<!DOCTYPE html>
<html>
<head>
	<title>music-rungis</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link rel="stylesheet" type="text/css" href="/static/reservation/css/styles.css" />

	<script type="text/javascript" src="/static/reservation/js/jquery/jquery-2.2.1.js"></script>
	  
	<style type="text/css">
    .jumbotron {
        background: #532f8c;
        color: white;
        padding-bottom: 80px
    }
    .jumbotron .btn-primary {
        background: #845ac7;
        border-color: #845ac7
    }
    .jumbotron .btn-primary:hover {
        background: #7646c1
    }
    .jumbotron p {
        color: #d9ccee;
        max-width: 75%;
        margin: 1em auto 2em
    }
    .navbar+.jumbotron {
        margin-top: -20px
    }
    .jumbotron .lang-logo {
        display: block;
        background: #b01302;
        border-radius: 50%;
        overflow: hidden;
        width: 100px;
        height: 100px;
        margin: auto;
        border: 2px solid white
    }
    .jumbotron .lang-logo img {
        max-width: 100%
    }
    .user-navbar {
    	background-color: lightgreen;
    	border-style: solid;
    	border-width: thin;
    }

  </style>
</head>

<body>

<div>
	<nav class="navbar navbar-default navbar-static-top navbar-inverse">
	  <div class="user-navbar">
		  <table>
		  	<tr>
		  		{% if current_version %}
		  			<td style="text-align: left;"><div class="small">Commission Musique Rungis - {{ current_version.version_name }} - {{ current_version.version_date }}</div></td>
		  		{% endif %}
		  		<td>
				  	<div class="small">
					  	{% if user.is_authenticated %}
					    	<p title="cliquer pour vous déconnecter">Bienvenue : {{ user.username }} - {{ user.email }} 
					    	<a href="{% url 'logout' %}?next=/">déconnexion</a>
					    	</p>
						{% else %}
					    	<p title="cliquer pour vous connecter">Bienvenue : <a href="{% url 'login' %}?next=/" >connexion</a>
					    	</p>
						{% endif %}
				  	</div>
		  		</td>
		  		<td>
		  			<div class="small">
		  				{% if user.is_staff or user.is_superuser %}
		  					<p title="cliquer pour ouvrir le site d'administration"><a href="{% url 'admin:index' %}" target="_blank">ouvrir le site d'administration</a>
		  					</p>
		  				{% endif %} 
		  			</div>
		  		</td>
		  		<td>
		  			<div class="small" align="right">
		  				{% if user.is_authenticated %}
						 	<p title="cliquer pour modifier son mot de passe"><a href="{% url 'password_change' %}?next=/">modifier mon mot de passe</a>
						 	</p>
					 	{% endif %}
		  			</div>
		  		</td>
				<td style="text-align: left;"><div class="small" title="cliquer pour envoyer un mail à un administrateur"><a href="mailto:robert.pastor0691@gmail.com?Subject=Site%20de%20la%20Commission%20Musique%20de%20Rungis" target="_top">envoyer un mail à un administrateur</a></div></td>
			</tr>
		  </table>
	  </div>
	</nav>

	<div class="main-container">
	{% block content %}
	
	{% endblock %}
	</div>

</div>

</body>
</html>

hello/templates/db.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
  <div class="container">


<h2>Page View Report</h2>


<ul>

{% for greeting in greetings %}
    <li>{{ greeting.when }}</li>
{% endfor %}

</ul>

</div>

{% endblock %}

hello/templates/index.html
{% extends "base.html" %}
{% load static %}

{% block content %}
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}" />
	<script type="text/javascript" src="/static/reservation/js/jquery/jquery-2.2.1.js"></script>
	<script type="text/javascript" src="/static/js/hello.js"></script>
	
	<link rel='shortcut icon' type='image/x-icon' href="{% static 'reservation/images/phare.ico' %}" />
	<script type="text/javascript">
		var siteMessages = {{ siteMessages|safe }};
	</script>
<head>
<body>
	<div class="jumbotron text-center">
	  <div class="container">
	  	<table >
	  		<tr >
	  			<td title="Commission Musique - Rungis" colspan="2">
	  				<div class="center">
	  					<img class="commission" src="{% static 'images/commission-musique.jpg'%}">
	  				</div>
	  			</td>
	  		</tr>
	  	
	    	<tr>
	    		<td>
	    			<h2 class="center"> Réservations de Studios </h2>
	    		</td>
	    		<td>
	    			<h2 class="center"> Echange de Partitions </h2>
	    		</td>
	    	</tr>
	    
			<tr>
				<td>
					<div class="center" title="cliquez-moi">
		    			<a type="button" class="btn btn-blue" href="{% url 'reservation:reservations' %}" ><span class="glyphicon glyphicon-flash"></span>réserver un studio</a>	
					</div>
				</td>
				<td>
					<div class="center" title="cliquez-moi">
		    			<a type="button" class="btn btn-blue" href="{% url 'partitions:partitions' %}" ><span class="glyphicon glyphicon-flash"></span>échanger des partitions</a>	
					</div>
				</td>
			</tr>
		</table>
	  </div>
	</div>
	<div>
		<h3 class="padding">Actualités</h3>
		<div>
			<table id="informations" class="informations" border="1" >
				<thead>
					<td class="padding bold"><span>Evénement ou Information</span></td>
					<td class="padding bold"><span>Date de l'événement</span></td>
				</thead>
				<tbody>
		
				</tbody>
			</table>
		</div>
		<div>
			<p class="small">Nota Bene: il est conseillé d'utiliser FireFox pour profiter pleinement des fonctionnalités de ce site.</p>
		</div>
		<div>
			<section class="center">
				<!--
			    <h1>Attention : Le 28 Novembre 2022 au plus tard, le site va migrer de Héroku vers PythonAnyWhere</h1>
			    <h2>Veuillez prendre contact avec un administrateur pour la recréation de votre compte</h2>
			    <h2>Voici la nouvelle adresse du site -> <a href="https://musicrungis.eu.pythonanywhere.com/" target="_blank">Music Rungis PythonAnyWhere</a></h2>
			    -->
			    <!-- 
				    <table>
				    	<tr>
				    		<td>
				    			<div class="center">
		  							<img class="hostingPlatformsHeroku" src="{% static 'images/heroku-logotype-vertical-purple.svg'%}">
		  						</div>
				    		</td>
				    		<td>
				    			<div class="center">
		  							<img class="hostingPlatforms" src="{% static 'images/pythonanywhere.png'%}">
		  						</div>
				    		</td>
				    	</tr>
				    </table>
			    -->
			</section>
		</div>
	</div>
</body>
{% endblock content  %}

hello/templates/tests.html
{% extends "base.html" %}
{% load staticfiles %}

{% block content %}
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<link rel="stylesheet" type="text/css" href="{% static 'css/tests.css' %}" />
	<script type="text/javascript" src="/static/js/tests.js"></script>
	
</head>

<div class="jumbotron text-center">
	
	<h2><a href="{% url 'index' %}">Tests</a></h2>
	  <div class="container">
	  	
	  	<table>
	  		<tr>
	  			<td class="tablink"><button class="tablink" onclick="openPage('Home', this, 'black')">Home</button></td>
	  			<td><button class="tablink" onclick="openPage('Reservations', this, 'green')" id="defaultOpen">Réservations</button></td>
	  			<td><button class="tablink" onclick="openPage('MenuContextuel', this, 'cyan')">Réservations - Menu Contextuel</button></td>
	  			<td><button class="tablink" onclick="openPage('Navigation', this, 'orange')">Changement de Période</button></td>
	  			<td><button class="tablink" onclick="openPage('SiteMessages', this, 'pink')">Messages du Site</button></td>
	  			<td><button class="tablink" onclick="openPage('Partitions', this, 'cyan')">Partitions</button></td>
	  			
	  			
	  		</tr>
	  	</table>
	  	
		<div id="Home" class="tabcontent">
		  <h3>Home</h3>
		  <p>Home is where anything starts...</p>
		</div>
		
		<div id="Navigation" class="tabcontent">
		  
			{% block navigation %}
   				{% include "tests/navigation.html" %}
			{% endblock %}
		  
		</div> 
		
		<div id="Reservations" class="tabcontent">
		
			{% block reservations %}
	   			{% include "tests/reservations.html" %}
			{% endblock %}
		  
		</div>
		
		<div id="MenuContextuel" class="tabcontent">

			{% block menu_contextuel %}
	   			{% include "tests/menu_contextuel.html" %}
			{% endblock %}		
			
		</div>
		
		<div id="SiteMessages" class="tabcontent">
		  
			{% block site_messages %}
   				{% include "tests/site_messages.html" %}
			{% endblock %}
		  
		</div> 
		
		<div id="Partitions" class="tabcontent">
		  <h3>Partitions</h3>
		  <p>à compléter.</p>
		</div>

	  </div>
</div>
{% endblock content  %}