gettingstarted/urls.py
#admin.autodiscover()

#from django.urls import include, re_path, path
from django.contrib import admin
admin.autodiscover()
from django.urls import include, re_path

from django.contrib.auth import views as auth_views
from hello.views import index, tests

app_name = "gettingstarted"

''' migration to Django 2.2 use re_path '''
urlpatterns = [
    re_path(r'^$', index, name='index'),

    re_path(r'^admin/', admin.site.urls ),
    
    re_path(r'^reservation/', include('reservation.urls') ),
    re_path(r'^partitions/', include('partitions.urls') ),

    re_path(r'^accounts/login/$', auth_views.LoginView.as_view(), name ='login'),
    re_path(r'^accounts/logout/$', auth_views.LogoutView.as_view() , name = 'logout' ),
    #re_path(r'^accounts/profile/$', index , name = 'index'),
    re_path(r'^tests/', tests, name='tests')
]

''' migration to Django 2.2 use re_path '''
urlpatterns += [
    re_path(r'^password_change/', auth_views.PasswordChangeView.as_view(), 
         {'template_name': 'registration/password_change_form.html'} ,name="password_change" ),
    
    re_path(r'^password_change_done/$', auth_views.PasswordChangeDoneView.as_view(), 
         {'template_name': 'registration/password_change_done.html'} ,name="password_change_done" ),
    ]

''' March 2024 - password reset '''
urlpatterns += [

    re_path(r'^password_reset/$', auth_views.PasswordResetView.as_view() ,
        { 'template_name': 'registration/password_reset_form', 'post_reset_redirect' : '/password_reset_done/'}, 
        name="password_reset"),
     
    re_path(r'^password_reset_done/$', auth_views.PasswordResetDoneView.as_view(), 
        { 'template_name' : 'registration/password_reset_done'} ,
        name="password_reset_done"  ) ,
         
    re_path(r'^password_reset_confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$', 
        auth_views.PasswordResetConfirmView.as_view() , 
        { 'template_name' : 'registration/password_reset_confirm'} ,
        name="password_reset_confirm" ),
     
    re_path(r'^password_reset_complete/$',
        auth_views.PasswordResetCompleteView.as_view() , 
        { 'template_name' : 'registration/password_reset_complete'} ,
        name="password_reset_complete" )
    
    ]

partitions/urls.py
from django.conf.urls import re_path

#from django.views.decorators.csrf import csrf_exempt
from partitions.views import partitions, recordNewPartition, deletePartition, modifyPartition

app_name = "partitions"

urlpatterns = [
               
    re_path(r'^$', partitions, name='partitions'),
    re_path(r'^recordNewPartition$', recordNewPartition , name = 'recordNewPartition'),
    re_path(r'^deletePartition$', deletePartition , name = 'deletePartition'),
    re_path(r'^modifyPartition$', modifyPartition , name = 'modifyPartition'),

]

reservation/urls.py
from django.conf.urls import re_path

from reservation.views.ManageBookings import addBooking, deleteBooking, modifyBooking, deleteOldBookings
from reservation.views.ManageReservations import reservations
from reservation.views.ManagePeriods import modifyPeriod
from reservation.views.WeeklyReservationsViews import generateWeeklyReservations
from reservation.views.ExcelOutput import createExcelOutput 
#from django.views.decorators.csrf import csrf_exempt

app_name = "reservation"

urlpatterns = [
    re_path(r'^$', reservations, name='reservations'),
    
    re_path(r'^modifyPeriod$', modifyPeriod , name = 'modifyPeriod'),
    re_path(r'^addBooking$', addBooking , name = 'addBooking'),
    re_path(r'^deleteBooking$', deleteBooking , name = 'deleteBooking'),
    re_path(r'^modifyBooking$', modifyBooking , name = 'modifyBooking'),
    re_path(r'^generateWeeklyReservations$', generateWeeklyReservations , name = 'generateWeeklyReservations'),
    re_path(r'^deleteOldBookings$', deleteOldBookings , name = 'deleteOldBookings'),
]

''' view to create an EXCEL file '''
urlpatterns += [
    re_path(r'^excel/$', createExcelOutput , name='createExcel'),
]

reservation/views.py
#-*- coding: utf-8 -*-
import locale
import json
import urllib
import copy

from datetime import datetime , timedelta, date
from pytz import timezone

from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth.decorators import login_required

from django.core import serializers

from django.http import HttpResponse
from django.template import loader

from django.contrib.auth.models import User

from gettingstarted.settings import TIME_ZONE
from reservation.models import Studio, Reservation

from reservation.BankHolidays import FrenchBankHolidays
from reservation.displayModeFile import DisplayMode
from reservation.StudioUsers import getStudioUsers
from reservation.versions.versionsFile import VersionsList

French_Locale = ""
encoding = 'utf-8'


class JSONDateTimeEncoder(json.JSONEncoder):
    def default(self, obj):
        paris = timezone(TIME_ZONE)
        #fmt = '%Y-%m-%d %H:%M:%S %Z%z'
        fmt = '%Y-%m-%dT%H:%M:%S'
        if isinstance(obj, (date, datetime)):
            loc_dt = obj.astimezone(paris)
            #print(loc_dt.strftime(fmt))
            return loc_dt.strftime(fmt)
        else:
            return json.JSONEncoder.default(self, obj)


def getReservations(displayMode, year, week_number):
    if displayMode.isWeeklyDisplayMode():
        return serializers.serialize('python', getFilteredReservations(year, week_number))
    else:
        return serializers.serialize('python', list(Reservation.objects.all()))


def getFilteredReservations(isoYear , isoWeekNumber):
    '''
    return only the reservations of the ISO week.
    '''
    #list(Reservation.objects.all().order_by("date_start","studio_key"))
    reservationsList = []
    ''' query reservations ordered by date_start and as second order the studio key '''
    for reservation in Reservation.objects.all().order_by("date_start", "studio_key"):
        #print ' iso year {0} and iso week {1} of the reservation'.format(reservation.date_start.isocalendar()[0] , reservation.date_start.isocalendar()[1])
        if ((reservation.date_start.isocalendar()[0] == isoYear) and (reservation.date_start.isocalendar()[1] == isoWeekNumber)):
            #print reservation
            reservationsList.append(reservation)
            
    return reservationsList


def lastISOWeekNumberOfPreviousYear(year):
    referenceFourthJanuary = datetime(year, 1, 4)
    #print 'reference 4th of January {0}'.format(referenceFourthJanuary)
    ''' week day returns 0 if monday '''
    dayIndexInTheFirstWeek = referenceFourthJanuary.weekday()
    ''' compute minus 5 days to be sure to move to previous year '''
    lastDayInPreviousYear = referenceFourthJanuary + timedelta(days=(-dayIndexInTheFirstWeek-1))
    #print 'last day of the previous ISO year = {0}'.format(lastDayInPreviousYear)
    #print 'previous ISO year= {0}'.format(lastDayInPreviousYear.isocalendar()[0])
    #print 'last ISO week of previous year= {0}'.format(lastDayInPreviousYear.isocalendar()[1])
    return lastDayInPreviousYear.isocalendar()[1]


def getMondayOfWeekYear(year, week):
    year = int(year)
    week = int(week)
    paris = timezone(TIME_ZONE)
    ''' utiliser datetime pour pouvoir ajouter des heures '''
    referenceThursday = paris.localize(datetime(year=year, month=1, day=4)) # Le 4 janvier est toujours en semaine 1
    dayInTheFirstWeek = referenceThursday.weekday()
    #print 'day of the 4th of January = {0}'.format(dayInTheFirstWeek)
    jours = 7*(week - 1) - dayInTheFirstWeek
    monday = referenceThursday + timedelta(days=jours)
    return monday
    

def weekDays(year, week):
    ''' utiliser datetime pour pouvoir ajouter des heures '''
    referenceThursday = datetime(year, 1, 4) # Le 4 janvier est toujours en semaine 1
    dayInTheFirstWeek = referenceThursday.weekday()
    #print 'day of the 4th of January = {0}'.format(dayInTheFirstWeek)
    jours = 7*(week - 1) - dayInTheFirstWeek
    lundi = referenceThursday + timedelta(days=jours)
    ''' send days in iso format - then up to javascript to create the french day and month '''
    ''' python 2 to python 3 xrange to range '''
    return [ (lundi + timedelta(days=n)).isoformat() for n in range(7)]


def semaine(annee, sem):
    ''' utiliser datetime pour pouvoir ajouter des heures '''
    ref = datetime(annee, 1, 4) # Le 4 janvier est toujours en semaine 1
    j = ref.weekday()
    jours = 7*(sem - 1) - j
    ''' si ref n'est pas du type datetime impossible de rajouter un timedelta '''
    lundi = ref + timedelta(days=jours)
    ''' python 2 to python 3 xrange to range '''
    return [lundi + timedelta(days=n) for n in range(7)]


def convertEnglish2French(selectedDate):
    if (str(selectedDate).startswith("Monday")):
        return 'lundi'
    elif (str(selectedDate).startswith("Tuesday")):
        return 'mardi'
    elif (str(selectedDate).startswith("Wednesday")):
        return 'mercredi'
    elif (str(selectedDate).startswith("Thursday")):
        return 'jeudi'
    elif (str(selectedDate).startswith("Friday")):
        return 'vendredi'
    elif (str(selectedDate).startswith("Saturday")):
        return 'samedi'
    else:
        return 'dimanche'
   

def computeSelectedDate(selectedDate, week_number, year):
    for day in semaine(year, week_number):
        #print day
        #print day.strftime('%A')
        if str(convertEnglish2French(selectedDate)).startswith(day.strftime('%A')):
            return day
    return None


@login_required
def reservations(request):
    locale.setlocale(locale.LC_TIME, French_Locale)

    template = loader.get_template('reservation/reservations.html')
    ''' send the current version to be displayed in the header '''
    versionsList = VersionsList()
    versionsList.fill()

    week_number = datetime.today().isocalendar()[1]
    year = datetime.today().isocalendar()[0]
    ''' provide the latest recorded version '''
    #print 'current version = {0}'.format(versionsList.first())
    
    context = {
        'week_number'       : week_number,
        'year'              : year,
        'current_version'   : versionsList.first()
    }
    return HttpResponse(template.render(context, request))


@login_required
def modifyPeriod(request):
    locale.setlocale(locale.LC_TIME, French_Locale)

    displayMode = DisplayMode()
    
    #print 'modify period - user = {user}'.format(user=request.user)
    #print request
    if (request.method == 'GET'):
        
        displayMode.initialise(request)
        year = 0
        week_number = 0
        month_number = 0
        if request.GET['action'] == 'first':
            ''' by default first is always in weekly mode '''
            week_number = datetime.today().isocalendar()[1]
            month_number = datetime.today().month
            #print 'modify period - month number = {0}'.format(month_number)
            year = datetime.today().isocalendar()[0]
            #print 'modify week first - year= {year} - week number= {week_number}'.format(year=year, week_number=week_number)
        
        elif request.GET['action'] == 'inc':
            ''' action = increment '''
            year = int(request.GET['year'])
            try:
                week_number = int(request.GET['week'])
                if (week_number):
                    if (week_number == lastISOWeekNumberOfPreviousYear(year+1)):
                        week_number = 1
                        year = year + 1
                    else:
                        week_number = week_number + 1
                    
                    ''' need to check whether a year changes occur here '''
            except:
                # there is no such week parameter in the get query
                week_number = 0
                try:
                    month_number = int(request.GET['month'])
                    if (month_number == 12):
                        year = year + 1
                except:
                    month_number = 0
        
        elif request.GET['action'] == 'dec':
            ''' action = decrement '''
            year = int(request.GET['year'])
            try:
                week_number = int(request.GET['week'])
                if (week_number):
                    if (week_number == 1):
                        week_number = lastISOWeekNumberOfPreviousYear(year)
                        year = year - 1
                    else:
                        week_number = week_number - 1
                        
                    #print 'modify week dec - year= {year} - week number= {week_number}'.format(year=year, week_number=week_number)

            except:
                week_number = 0
                try:
                    month_number = int(request.GET['month'])
                    if (month_number == 1):
                        year = year - 1
                except:
                    month_number = 0                   
            
        else:
            week_number = datetime.today().isocalendar()[1]
            month_number = datetime.today.month + 1
            year = datetime.today().isocalendar()[0]
            #print 'modify week first - year= {year} - week number= {week_number}'.format(year=year, week_number=week_number)
            
        #print 'modified week number = {0}'.format(week_number)
        ''' retrieve only users having done a reservation '''
        #users = serializers.serialize('json', list(User.objects.all()), fields=('username','first_name','last_name','email','is_superuser','is_active', 'is_staff'))
        users = getStudioUsers(current_user=request.user)
        studios = serializers.serialize('json', list(Studio.objects.all()))
        ''' if 2 reservations on the same date time slot then studio 1 before studio 2 '''

        ''' always return reservations depending upon the display mode weekly or monthly '''
        reservations = getReservations(displayMode, year, week_number)
        
        response_data = {
                    'current_user_id': request.user.id,

reservation/views/ManageReservations.py
'''
Created on 15 oct. 2022

@author: robert
'''

import locale
from datetime import datetime 

from django.core import serializers
from django.contrib.auth.decorators import login_required
from django.template import loader
from django.http import HttpResponse

from reservation.models import  Reservation
from reservation.versions.versionsFile import VersionsList

French_Locale = ""
encoding = 'utf-8'

def getReservations(displayMode, year, week_number):
    if displayMode.isWeeklyDisplayMode():
        return serializers.serialize('python', getFilteredReservations(year, week_number))
    else:
        return serializers.serialize('python', list(Reservation.objects.all()))
    
    
def getFilteredReservations(isoYear , isoWeekNumber):
    '''
    return only the reservations of the ISO week.
    '''
    #list(Reservation.objects.all().order_by("date_start","studio_key"))
    reservationsList = []
    ''' query reservations ordered by date_start and as second order the studio key '''
    for reservation in Reservation.objects.all().order_by("date_start", "studio_key"):
        #print ' iso year {0} and iso week {1} of the reservation'.format(reservation.date_start.isocalendar()[0] , reservation.date_start.isocalendar()[1])
        if ((reservation.date_start.isocalendar()[0] == isoYear) and (reservation.date_start.isocalendar()[1] == isoWeekNumber)):
            #print reservation
            reservationsList.append(reservation)
            
    return reservationsList


@login_required
def reservations(request):
    locale.setlocale(locale.LC_TIME, French_Locale)

    template = loader.get_template('reservation/reservations.html')
    ''' send the current version to be displayed in the header '''
    versionsList = VersionsList()
    versionsList.fill()

    week_number = datetime.today().isocalendar()[1]
    year = datetime.today().isocalendar()[0]
    ''' provide the latest recorded version '''
    #print 'current version = {0}'.format(versionsList.first())
    
    context = {
        'week_number'       : week_number,
        'year'              : year,
        'current_version'   : versionsList.first()
    }
    return HttpResponse(template.render(context, request))

reservation/views/StudioUsers.py
'''
Created on 30 juil. 2016

Purpose : to retrieve only users that are owner of a reservation

@author: PASTOR Robert
'''

from reservation.models import Reservation
from django.core import serializers

def getStudioUsers(current_user):
    ''' use a set to avoid duplicates '''
    studio_users_list = set()
    for reservation in Reservation.objects.all():
        #print reservation.made_by
        studio_users_list.add(reservation.made_by)

    ''' add the current user '''
    studio_users_list.add(current_user)
    ''' serialize : 23 September 2016 - do not send email nor passwords '''
    studio_users = serializers.serialize('json', list(studio_users_list), fields=('username','first_name','last_name','is_superuser','is_active', 'is_staff'))
    #print studio_users
    return studio_users

reservation/templates/reservation/reservations - Copie.html
{% extends "base.html" %}

{% load staticfiles %}
{% block content %}
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
	
	<link type="text/css" rel="stylesheet" href="/static/reservation/css/daypilot/calendar_green.css" />
	<link type="text/css" rel="stylesheet" href="/static/reservation/css/daypilot/month_green.css" />
	
	<link type="text/css" rel="stylesheet" href="/static/reservation/css/Site.css" />
	<link type="text/css" rel="stylesheet" href="/static/reservation/css/jquery/jquery-ui.css" />
	<link type="text/css" rel="stylesheet" href="/static/reservation/css/jquery/jquery.contextMenu.css" />
	
	<link rel='shortcut icon' type='image/x-icon' href="{% static 'reservation/images/phare.ico' %}" />

	<script type="text/javascript" src="/static/reservation/js/jquery/jquery-2.2.1.js"></script>
	<script type="text/javascript" src="/static/reservation/js/jquery/jquery-ui.js"></script>
	<script type="text/javascript" src="/static/reservation/js/jquery/jquery.ui.position.js" ></script>
	<script type="text/javascript" src="/static/reservation/js/jquery/jquery.contextMenu.js" ></script>
	<script type="text/javascript" src="/static/reservation/js/jquery/jquery.jeditable.js" charset="utf-8"></script>
	
	<script type="text/javascript" src="/static/reservation/js/toolBox.js"></script>

	<script type="text/javascript" src="/static/reservation/js/daypilot/src/daypilot-common.src.js" ></script>
	<script type="text/javascript" src="/static/reservation/js/daypilot/src/daypilot-datepicker.src.js" ></script>
	<script type="text/javascript" src="/static/reservation/js/daypilot/src/daypilot-modal.src.js" ></script>
	<script type="text/javascript" src="/static/reservation/js/daypilot/src/daypilot-month.src.js" ></script>
	<script type="text/javascript" src="/static/reservation/js/daypilot/src/daypilot-navigator.src.js" ></script>
	<script type="text/javascript" src="/static/reservation/js/daypilot/src/daypilot-calendar.src.js" ></script>
	
	<script type="text/javascript" src="/static/reservation/js/IsoWeek.js"   ></script>
	<script type="text/javascript" src="/static/reservation/js/help/help.js"   ></script>
	<script type="text/javascript" src="/static/reservation/js/Site.js"   ></script>	

</head>

<table width="100%" height="100%" border='1px'>
	<tr>
		<td class="header" width="10%">
		
			<div class="reload" type="image" onclick="reloadCurrentPeriod()" title="cliquez pour retourner à la période courante"></div>
			
		</td>
		<td class="header" rowspan="2"><div type="image" class="previous_period" id="btnPreviousPeriod" title="cliquez pour passer à la période précédente"></div></td>
		<td class="silver" colspan="5">
					
			<table>
				<tr>
					<td>
						<div class="center silver"> cliquez sur une flèche pour changer de période </div>
					</td>
				</tr>
					<td>
						<div><marquee behavior="scroll" direction="left" class="small"> ...Veuillez utiliser le click droit sur une réservation pour accéder à un menu contextuel... </marquee></div>
					</td>
				<tr>
					<td>
						<div><marquee behavior="scroll" direction="right" class="small"> ...Pensez à supprimer les anciennes réservations dont vous êtes le propriétaire... </marquee></div>
					</td>
				</tr>
			</table>
					
		</td>
		
		<td class="silver" id="td_form_message" style='text-align: center; display: none;' rowspan="2">
			<div id='form_message' style='text-align: center; display: none;'>
                <img src='/static/reservation/images/gif_anime_puces.gif' style="width:24px;height:24px;border:0" />
                <br />
                <div id='form_message_text' class="form_message_text"></div>
            </div>
		</td>
		
		<td class="header" rowspan="2"><div type="image" class="next_period" id="btnNextPeriod"  title="cliquez pour passer à la période suivante"></div></td>
		<td class="question_mark_bg" rowspan="2"><div class="question_mark" type="image" onclick="showHelp()" title="cliquez pour obtenir de l'aide"></div></td>
	</tr>
	<tr>
		<td class="header" width="10%">
			<table>
				<tr>
					<td>
						<div class="toggleMonthWeek" title="cliquez pour changer le mode de présentation"><a href="#" class="toggler">Mensuel</a></div>
					</td>
					<td>
						<div id="weeklyReservationsDivId" title="cliquez pour générer les réservations périodiques de la semaine" onclick="generateWeeklyReservations()" ><img class="weeklyReservations" src='/static/reservation/images/piano.png' /></div>
					</td>
					<td>
						<div id="deleteOldWeeklyReservationsDivId" title="cliquez pour supprimer les anciennes réservations de la semaine courante." onclick="deleteOldReservations()" ><img class="trashBin" src='/static/reservation/images/trashBin.png' /></div>
					</td>
					
				</tr>
			</table>
			
		</td>
		<td class="silver"><div id="labelWeekMonth" class="center silver">Semaine</div></td>
		<td class="silver">
			<div class="weekNumber" id="weekNumber"></div>
			<div class="monthNumber" id="monthNumber" style="display: none;"></div>
		</td>

		<td class="silver">		
			<div class="pointer" title="cliquez pour obtenir une sortie EXCEL">
				<!--  <a id="excel" href="{% url 'createExcel' %}">  -->
				<!--   <img src="/static/reservation/images/Excel-icon.png" style="width:24px;height:24px;border:0"> -->
				<!--   </a> -->
			</div>							
		</td>
		<td class="silver"><div class="center silver" >Année</div></td>
		<td class="silver"><div class="year" id="year"></div></td>
	</tr>

</table>

<div id="dialogCreate"></div>
<div id="dialogResize"></div>
<div id="dialogMove"></div>
<div id="dialogDelete"></div>
<div id="dialogModify"></div>

<div>
	<div id="dp"></div>
</div>

<div id="dialog-confirm" class="song"></div>

<div id="dialog-details"></div>
<div id="helpDiv" style="display: none;"></div>
<div id="versions" style="display: none;">
	<table>
		<thead></thead>
		<tbody></tbody>
	</table>
</div>
<div id="overlay" class="overlay">
	<img class="loading-indicator" />
</div>

{% endblock content %}

reservation/templates/reservation/reservations.html
{% extends "base.html" %}

{% load static %}
{% block content %}
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	
	
	<link type="text/css" rel="stylesheet" href="/static/reservation/css/daypilot/calendar_green.css" />
	<link type="text/css" rel="stylesheet" href="/static/reservation/css/daypilot/month_green.css" />
	
	<link type="text/css" rel="stylesheet" href="/static/reservation/css/site.css" />
	<link type="text/css" rel="stylesheet" href="/static/reservation/css/jquery/jquery-ui.css" />
	<link type="text/css" rel="stylesheet" href="/static/reservation/css/jquery/jquery.contextMenu.css" />
	
	<link rel='shortcut icon' type='image/x-icon' href="{% static 'reservation/images/phare.ico' %}" />

	<script type="text/javascript" src="/static/reservation/js/jquery/jquery-2.2.1.js"></script>
	<script type="text/javascript" src="/static/reservation/js/jquery/jquery-ui.js"></script>
	<script type="text/javascript" src="/static/reservation/js/jquery/jquery.ui.position.js" ></script>
	<script type="text/javascript" src="/static/reservation/js/jquery/jquery.contextMenu.js" ></script>
	<script type="text/javascript" src="/static/reservation/js/jquery/jquery.jeditable.js" charset="utf-8"></script>
	<script type="text/javascript" src="/static/reservation/js/jquery/jquery.mousewheel.js" charset="utf-8"></script>
	
	<script type="text/javascript" src="/static/reservation/js/toolBox.js"></script>

	<script type="text/javascript" src="/static/reservation/js/daypilot/src/daypilot-common.src.js" ></script>
	<script type="text/javascript" src="/static/reservation/js/daypilot/src/daypilot-datepicker.src.js" ></script>
	<script type="text/javascript" src="/static/reservation/js/daypilot/src/daypilot-modal.src.js" ></script>
	<script type="text/javascript" src="/static/reservation/js/daypilot/src/daypilot-month.src.js" ></script>
	<script type="text/javascript" src="/static/reservation/js/daypilot/src/daypilot-navigator.src.js" ></script>
	<script type="text/javascript" src="/static/reservation/js/daypilot/src/daypilot-calendar.src.js" ></script>
	
	<script type="text/javascript" src="/static/reservation/js/IsoWeek.js"   ></script>
	<script type="text/javascript" src="/static/reservation/js/help/help.js"   ></script>
	<script type="text/javascript" src="/static/reservation/js/site.js"   ></script>	

</head>


	<div class="main" >

	<table class="table_reservation">
		<tr>
			<td class="header" width="10%">
			
				<div class="reload" onclick="reloadCurrentPeriod()" title="cliquez pour retourner à la période courante"></div>
				
			</td>
			<td class="header" rowspan="2"><div class="previous_period" id="btnPreviousPeriod" title="cliquez pour passer à la période précédente"></div></td>
			<td class="silver" colspan="5">
							
					<table>
						<tr>
							<td>
								<div class="center silver"> cliquez sur une flèche pour changer de période </div>
							</td>
						</tr>
						<tr>
							<td>
								<div><marquee behavior="scroll" direction="left" class="small"> ...Veuillez utiliser le click droit sur une réservation pour accéder à un menu contextuel... </marquee></div>
							</td>
						</tr>
						<tr>
							<td>
								<div><marquee behavior="scroll" direction="right" class="small"> ...Pensez à supprimer les anciennes réservations dont vous êtes le propriétaire... </marquee></div>
							</td>
						</tr>
					</table>
							
				</td>
				
				<td class="silver" id="td_form_message" style='text-align: center; display: none;' rowspan="2">
					<div id='form_message' style='text-align: center; display: none;'>
		                <img src='/static/reservation/images/gif_anime_puces.gif' style="width:24px;height:24px;border:0" />
		                <br />
		                <div id='form_message_text' class="form_message_text"></div>
		            </div>
				</td>
				
				<td class="header" rowspan="2">
					<div class="next_period" id="btnNextPeriod"  title="cliquez pour passer à la période suivante"></div>
				</td>
				<td class="question_mark_bg" rowspan="2">
					<div class="question_mark" onclick="showHelp()" title="cliquez pour obtenir de l'aide"></div>
				</td>
			</tr>
			<tr>
				<td class="header" width="10%">
				
					<table>
						<tr>
							<td>
								<div class="toggleMonthWeek" title="cliquez pour changer le mode de présentation"><a href="#" class="toggler">Mensuel</a></div>
							</td>
							<td>
								<div id="weeklyReservationsDivId" title="cliquez pour générer les réservations périodiques de la semaine" onclick="generateWeeklyReservations()" ><img class="weeklyReservations" src='/static/reservation/images/piano.png' /></div>
							</td>
							<td>
								<div id="deleteOldWeeklyReservationsDivId" title="cliquez pour supprimer les anciennes réservations de la semaine courante." onclick="deleteOldReservations()" ><img class="trashBin" src='/static/reservation/images/trashBin.png' /></div>
							</td>
							
						</tr>
					</table>
					
				</td>
				<td class="silver"><div id="labelWeekMonth" class="center silver">Semaine</div></td>
				<td class="silver">
					<div class="weekNumber" id="weekNumber"></div>
					<div class="monthNumber" id="monthNumber" style="display: none;"></div>
				</td>
		
				<td class="silver">		
					<div class="pointer" title="cliquez pour obtenir une sortie EXCEL">
						<a id="excel" href="{% url 'reservation:createExcel' %}">  
							<img src="/static/reservation/images/Excel-icon.png" style="width:24px;height:24px;border:0"> 
						</a>
					</div>							
				</td>
				<td class="silver"><div class="center silver" >Année</div></td>
				<td class="silver"><div class="year" id="year"></div></td>
			</tr>
		
		</table>
		
		<div id="dialogCreate"></div>
		<div id="dialogResize"></div>
		<div id="dialogMove"></div>
		<div id="dialogDelete"></div>
		<div id="dialogModify"></div>
		
		<div>
			<div id="dp"></div>
		</div>
		
		<div id="dialog-confirm" class="song"></div>
		
		<div id="dialog-details"></div>
		<div id="helpDiv" style="display: none;"></div>
		<div id="versions" style="display: none;">
			<table>
				<thead></thead>
				<tbody></tbody>
			</table>
		</div>
		<div id="overlay" class="overlay">
			<img class="loading-indicator" />
		</div>
		
	</div>


{% endblock content %}